// Auth Types

//Home Types
export const SAVE_USER = 'SAVE_USER';
export const SAVE_RECIPIES = 'SAVE_RECIPIES';
export const SAVE_HOME_RECIPIES = 'SAVE_HOME_RECIPIES';
export const SAVE_LUNCH_RECIPIES = 'SAVE_LUNCH_RECIPIES';
export const SAVE_DINNER_RECIPIES = 'SAVE_DINNER_RECIPIES';
export const SAVE_BREAKFAST_RECIPIES = 'SAVE_BREAKFAST_RECIPIES';
export const SAVE_ALL_RECIPIES = 'SAVE_ALL_RECIPIES';
export const SAVE_HOT_RECIPIES = 'SAVE_HOT_RECIPIES';
